import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/page";
import Footer from "@/components/Footer/page";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Navbar ko body ke andar hona chahiye */}
      <body className="min-h-full flex flex-col">
        <Navbar />
        <main className="flex-grow">
          {children}

        </main>
        <Footer />
      </body>
    </html>
  );
}
